check parent directories for .clang-format

diff --git a/clang-format-all b/clang-format-all
--- a/clang-format-all
+++ b/clang-format-all
@@ -53,11 +53,23 @@ for dir in "$@"; do
     fi
 done
 
+# Find a dominating file, starting from a given directory and going up.
+find-dominating-file() {
+    if [ -r "$1"/"$2" ]; then
+        return 0
+    fi
+    if [ "$1" = "/" ]; then
+        return 1
+    fi
+    find-dominating-file "$(realpath "$1"/..)" "$2"
+    return $?
+}
+
 # Run clang-format -i on all of the things
 for dir in "$@"; do
-    pushd "${dir}"
-    if [ ! -r .clang-format ]; then
-        echo "no .clang-format in pwd $PWD"
+    pushd "${dir}" &>/dev/null
+    if ! find-dominating-file . .clang-format; then
+        echo "Failed to find dominating .clang-format starting at $PWD"
         continue
     fi
     find . \
@@ -68,5 +80,5 @@ for dir in "$@"; do
          -o -name '*.hh' \
          -o -name '*.hpp' \) \
          -exec "${FMT}" -i '{}' \;
-    popd
+    popd &>/dev/null
 done
